language: python
python:
  - "3.3"
install:
  - pip install flake8
  - pip install flake8-docstrings
  - pip install pep8-naming
  - pip install pytest
addons:
  apt:
    packages:
      - aspell
      - aspell-en
script:
  - py.test .
  - flake8 .
  - python spellcheck.py
